CREATE TABLE receipts (
	id INT PRIMARY KEY AUTO_INCREMENT,
	buyer VARCHAR(256) NOT NULL,
  date timestamp NOT NULL
);

CREATE TABLE products (
	id INT PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(256) NOT NULL UNIQUE,
	price DOUBLE NOT NULL,
	receipt_id INT,
	FOREIGN KEY (receipt_id)
	    REFERENCES receipts(id)
	    ON UPDATE CASCADE
);